apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: backend-kafka-source
  labels:
    app.kubernetes.io/instance: backend-kafka-source
    app.kubernetes.io/part-of: eda-workshop-serverless 
    kafkasources.sources.knative.dev/key-type: int
spec:
  consumerGroup: backend-knative-group
  bootstrapServers:
    - event-bus-kafka-bootstrap.eda-workshop.svc:9092
  topics:
    - 'eda.data.accounts'
    - 'eda.data.clients'
    - 'eda.data.movements'
    - 'eda.events.domain.clients'
    - 'eda.events.domain.accounts'
    - 'eda.events.domain.regions'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: backend-serverless
