---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: eda-workshop
spec:
  channel: beta
  installPlanApproval: Automatic
  #name: prometheus
  name: rhods-prometheus-operator
  #source: community-operators
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: prometheusoperator.0.56.3
  startingCSV: rhods-prometheus-operator.4.10.0
