apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: event-bus
  name: eda.cloud.events
spec:
  config:
    min.insync.replicas: "2"
    retention.ms: "7200000"
    segment.bytes: "1073741824"
  partitions: 10
  replicas: 3
