---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend-serverless
  labels:
    app.kubernetes.io/instance: data-streaming-serverless
    app.kubernetes.io/part-of: eda-workshop-serverless
spec:
  template:
    metadata:
      annotations:
        # Determines the minimum amount of time that the last pod will remain active after
        # the Autoscaler decides to scale pods to zero.
        autoscaling.knative.dev/scaleToZeroPodRetentionPeriod: "5s"    
      labels:
        app.kubernetes.io/instance: backend-serverless
        app.kubernetes.io/part-of: eda-workshop-serverless
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/eda-workshop/backend:2.16.5-SNAPSHOT
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
