---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: data-streaming-native-serverless
  labels:
    app.kubernetes.io/instance: data-streaming-native-serverless
    app.kubernetes.io/part-of: eda-workshop-serverless-native
spec:
  template:
    metadata:
      annotations:
        # Determines the minimum amount of time that the last pod will remain active after
        # the Autoscaler decides to scale pods to zero.
        autoscaling.knative.dev/scaleToZeroPodRetentionPeriod: "5s"
        ## Knative concurrency-based autoscaling (default).
        #autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        #autoscaling.knative.dev/metric: concurrency
        #autoscaling.knative.dev/metric: rps
        ## Target 10 requests in-flight per pod.
        #autoscaling.knative.dev/target: "10"
        ## Disable scale to zero with a minScale of 1.
        #autoscaling.knative.dev/minScale: "1"
        # Limit scaling to 100 pods.
        autoscaling.knative.dev/maxScale: "10"
        ## Standard Kubernetes CPU-based autoscaling.
        #autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
        #autoscaling.knative.dev/metric: cpu
        #autoscaling.knative.dev/target: "50"
      labels:
        app.kubernetes.io/instance: data-streaming-native-serverless
        app.kubernetes.io/part-of: eda-workshop-serverless-native
    spec:
      containers:
        - image: quay.io/eda-workshop/data-streaming:2.10.1-SNAPSHOT
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 1Gi
